# Augmentation configuration for Albumentations

train:
  - name: RandomResizedCrop
    params: {height: 224, width: 224, scale: [0.8, 1.0], ratio: [0.75, 1.3333]}
  - name: HorizontalFlip
    params: {p: 0.5}
  - name: RandomBrightnessContrast
    params: {p: 0.5, brightness_limit: 0.2, contrast_limit: 0.2}
  - name: Blur
    params: {p: 0.2, blur_limit: 3}
  - name: JPEGCompression
    params: {p: 0.2, quality_lower: 70, quality_upper: 100}
  - name: RandomErasing
    params: {p: 0.2, scale: [0.02, 0.33], ratio: [0.3, 3.3]}

val:
  - name: Resize
    params: {height: 224, width: 224}